---
- name: install docker.io
  hosts: all
  become: yes
  
  tasks:
  - name: Ensure docker package is present
    apt:
     name: docker.io
     state: present
  - name: Ensure docker.service  is present
    service: 
     name: docker
     state: started
  - name: Ensure git package is present
    apt:
     name: git
     state: present
  

- name: make bild
  hosts: bild
  become: yes

  tasks:
  - name: Copy file to builder  
    copy: 
     src: builder/Dockerfile
     dest: /app/
     state: directory