---
- name: install docker.io
  hosts: all
  become: yes
  
  tasks:
  - name: Ensure docker package is present
    apt:
     name: docker.io
     state: present
  - name: Ensure docker.service  is present
    service: 
     name: docker
     state: started
  - name: Ensure docker-compose package is present
    apt:
     name: docker-compose
     state: present
  - name: docker-python3
    apt:
      name: python3-docker
      state: present
  

- name: make bild
  hosts: bild
  become: yes
  
  tasks:
  - name: Creates directory
    file:
     path: /app/
     state: directory

  - name: Copy file to builder
    synchronize: 
      src: maven
      dest: /app/
  
  - name: Create a volume
    docker_volume:
      name: volume_one


  - name: Build image 
    docker_image:
     name: myimage
     build:
       path: /app/maven/builder/
     source: build

  - name: run container
    docker_container:
      name: builder
      image: myimage
      volumes:
      - volume_one:/opt/tomcat/latest/webapps/
      recreate: yes


  
  - name: Fetch .war
    fetch:
      src:  /var/lib/docker/volumes/volume_one/_data/hello-1.0.war
      dest: '{{playbook_dir}}/'
      flat: yes

- name: make prod
  hosts: prod
  become: yes

  tasks:
  - name: Create a volume
    docker_volume:
      name: volume_one

  - name: run container prod
    docker_container:
      name: prod
      image: davidcaste/alpine-tomcat:jre8tomcat7
      volumes:
      - volume_one:/opt/tomcat/latest/webapps/
      ports:
      - "8080:8080"
      state: present
#  - name: Creates directory
#    file:
#     path: /app/
#     state: directory
#
#  - name: Copy file to builder  
#    synchronize: 
#     src: tomcat
#     dest: /app/

 # - name: run docker-compose
 #   shell:
 #     cmd: docker-compose -f /app/tomcat/docker-compose.yml up -d
  
  - name: Copy .war
    copy:
      src: '{{playbook_dir}}/hello-1.0.war'
      dest: /var/lib/docker/volumes/tomcat_data-vol/_data/hello-1.0.war
     