---
- name: install docker.io
  hosts: all
  become: yes
  
  tasks:
  - name: Ensure docker package is present
    apt:
     name: docker.io
     state: present
  - name: Ensure docker.service  is present
    service: 
     name: docker
     state: started
  - name: Ensure git package is present
    apt:
     name: docker-compose
     state: present
  

- name: make bild
  hosts: bild
  become: yes

  tasks:
  - name: Creates directory
    file:
     path: /app/
     state: directory

  - name: Copy file to builder  
    synchronize: 
     src: maven
     dest: /app/

  - name: run docker-compose
    shell:
      cmd: docker-compose -f /app/maven/docker-compose.yml up -d
  
  - name: Fetch .war
    fetch:
      src: /var/lib/docker/volumes/maven_data-vol/_data/hello-1.0.war
      dest: '{{playbook_dir}}'
     